# Project Information
site_name: Compiler Wiki
site_description: Compiler Wiki 是关于编译器的相关知识
site_author: wangziwenhk
strict: true

nav:
  - 简介:
    - 开始: index.md
    - 关于本项目: start/project.md
    - 如何贡献: start/contribution.md

theme:
  name: material
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
  plugins:
    - search:
      title: '搜索'
    - livereload
    - latex
    - optimize
    
extra:
  version:
    method: mike

extra_css:
  - extra/css/extra.css
    
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex
  - admonition
  - pymdownx.details
  - toc:
      title: '目录'
      permalink: true
